on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

name: Daily

jobs:
  list_files:
      name: Build & Run
      runs-on: ubuntu-latest
      steps:
        - run: ls -la && pwd
          name: 'List files'
          
