on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

name: Daily

jobs:
  build_and_run:
      name: Build & Run
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          name: 'Checkout scraper'
          with:
            repository: 'kiros-rs/dynamixel-scraper'
        - uses: actions-rs/toolchain@v1.0.6
          name: 'Install toolchain'
          with:
            toolchain: nightly
        - run: sudo apt-get install -y libudev-dev
          name: 'Install libudev'
        - uses: actions-rs/cargo@v1.0.1
          name: 'Build scraper'
          with:
            command: build
        - run: 'sudo cp target/debug/dynamixel-scraper /bin'
          name: 'Install binary'
        - uses: actions/checkout@v2
          name: 'Checkout tables'
          with:
            repository: 'kiros-rs/control-tables'
        - run: 'dynamixel-scraper'
          name: 'Run scraper'
        - uses: EndBug/add-and-commit@v7.2.1
          name: 'Commit changes'
          with:
            add: "['tables', 'objects']"
            default_author: github_actions
            message: 'Daily table update'
            push: true
        - uses: actions/upload-artifact@v2.2.3
          name: 'Upload CSV artifacts'
          with:
            name: CSV
            path: tables/
        - uses: actions/upload-artifact@v2.2.3
          name: 'Upload RON artifacts'
          with:
            name: RON
            path: objects/
          
