on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

name: Daily

jobs:
  list_files:
      name: Build & Run
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          name: 'Checkout dynamixel-scraper repository'
          with:
            repository: 'kiros-rs/dynamixel-scraper'
            path: 'dynamixel-scraper'
        - uses: actions-rs/toolchain@v1.0.6
          name: 'Install nightly toolchain'
          with:
            toolchain: nightly
        - run: 'cd $GITHUB_WORKSPACE/dynamixel-scraper && cargo build'
          name: 'Build scraper'
        - uses: actions/checkout@v2
          name: 'Checkout control-tables repository'
          with:
            repository: 'kiros-rs/control-tables'
            path: lib
        - run: 'cd $GITHUB_WORKSPACE && dynamixel-scraper/target/debug/dynamixel-scraper --lib && cd lib'
          name: 'Run scraper'
        - uses: EndBug/add-and-commit@v7.2.1
          name: 'Commit changes'
          with:
            add: "['lib']"
            default_author: github_actions
            message: 'Daily table update'
            push: true
# This should be fixed later
#        - uses: actions/upload-artifact@v2.2.3
#          name: 'Upload CSV artifacts'
#          with:
#            name: CSV
#            path: tables/
#        - uses: actions/upload-artifact@v2.2.3
#          name: 'Upload RON artifacts'
#          with:
#            name: RON
#            path: objects/
