on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

name: Daily

jobs:
  build_and_run:
      name: Build & Run
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          name: 'Checkout'
          with:
            repository: 'kiros-rs/dynamixel-scraper'
        - uses: actions-rs/toolchain@v1.0.6
          name: 'Install toolchain'
          with:
            toolchain: nightly
        - run: sudo apt-get install -y libudev-dev
          name: 'Install libudev'
        - uses: actions-rs/cargo@v1.0.1
          name: 'Run scraper'
          with:
            command: run
            args: --release
        - uses: EndBug/add-and-commit@v7.2.1
          name: 'Commit changes'
          with:
            add: "['tables', 'objects']"
            default_author: github-actions
            message: 'Daily table update'
            push: true
